// Generated by WaveDSL

// assert block: aw_handshake
property aw_handshake;
    @(posedge clk) $rose(awvalid) |->
        (awvalid == 1'b1 && awready == 1'b0)[*2] ##1
        (awvalid == 1'b1 && awready == 1'b1) ##1
        (awvalid == 1'b1 && awready == 1'b0) ##1
        (awvalid == 1'b0 && awready == 1'b0)[*4];
endproperty
assert property (aw_handshake);

// assert block: axi_write_rules
property axi_write_rules_0;
    @(posedge clk) ((awvalid == 1'b1) && (awready == 1'b1)) |->
        (wvalid == 1'b1);
endproperty
assert property (axi_write_rules_0);
property axi_write_rules_1;
    @(posedge clk) ((awvalid == 1'b1) && (awready == 1'b1)) |->
        ##1 (wready == 1'b1);
endproperty
assert property (axi_write_rules_1);
property axi_write_rules_2;
    @(posedge clk) ($rose(wvalid)) |->
        ((wvalid == 1'b1))[*4];
endproperty
assert property (axi_write_rules_2);
