// Generated by WaveDSL

// assert block: burst_timing
property burst_timing;
    @(posedge clk) $rose(burst) |->
        (burst == 8'hAB && valid == 1'b1)[*2] ##1
        (burst == 8'hCD && valid == 1'b1)[*2] ##1
        (burst == 8'hAB && valid == 1'b1)[*2] ##1
        (burst == 8'hCD && valid == 1'b1)[*2] ##1
        (burst == 8'hAB && valid == 1'b1)[*2] ##1
        (burst == 8'hCD && valid == 1'b1)[*2] ##1
        (burst == 8'hAB && valid == 1'b1)[*2] ##1
        (burst == 8'hCD && valid == 1'b1)[*2] ##1
        (valid == 1'b0);
endproperty
assert property (burst_timing);

// assert block: burst_rules
property burst_rules_0;
    @(posedge clk) (valid == 1'b1) |->
        ((burst !== 'x && burst !== 'z));
endproperty
assert property (burst_rules_0);
property burst_rules_1;
    @(posedge clk) ($rose(valid)) |->
        (((burst !== 'x && burst !== 'z)))[*16];
endproperty
assert property (burst_rules_1);
property burst_rules_2;
    @(posedge clk) ($fell(valid)) |->
        (burst === 'x);
endproperty
assert property (burst_rules_2);
