// Generated by WaveDSL

// assert block: spi_transaction
property spi_transaction;
    @(posedge clk) $fell(cs_n) |->
        (cs_n == 1'b0 && (mosi !== 'x && mosi !== 'z))[*2] ##1
        (cs_n == 1'b0 && mosi == 8'hA5)[*4] ##1
        (cs_n == 1'b1);
endproperty
assert property (spi_transaction);

// assert block: spi_protocol_rules
property spi_protocol_rules_0;
    @(posedge clk) (cs_n == 1'b0) |->
        (mosi !== 'x);
endproperty
assert property (spi_protocol_rules_0);
property spi_protocol_rules_1;
    @(posedge clk) (cs_n == 1'b1) |->
        (mosi === 'x);
endproperty
assert property (spi_protocol_rules_1);
property spi_protocol_rules_2;
    @(posedge clk) ($rose(cs_n)) |->
        ##1 (mosi === 'x);
endproperty
assert property (spi_protocol_rules_2);
