// Generated by WaveDSL

// assert block: valid_data_combo
property valid_data_combo_0;
    @(posedge clk) (valid == 1'b1) |->
        (d_bus !== 'x);
endproperty
assert property (valid_data_combo_0);
property valid_data_combo_1;
    @(posedge clk) ($rose(valid)) |->
        ##2 (d_bus !== 'x);
endproperty
assert property (valid_data_combo_1);
