// Generated by WaveDSL

// assert block: burst_protocol
property burst_protocol;
    @(posedge clk) $rose(valid) |->
        (valid == 1'b1 && data == 8'hAB)[*4] ##1
        (valid == 1'b0)[*2];
endproperty
assert property (burst_protocol);
