use crate::ast::*;
use crate::error::Span;

/// Generate SystemVerilog assertions, or `None` if no assert blocks are present.
pub fn generate_sv(program: &Program) -> Option<String> {
    let blocks: Vec<&AssertBlock> = program
        .statements
        .iter()
        .filter_map(|s| {
            if let Statement::AssertBlock(b) = s {
                Some(b)
            } else {
                None
            }
        })
        .collect();

    if blocks.is_empty() {
        return None;
    }

    let mut out = String::from("// Generated by WaveDSL\n");
    for block in &blocks {
        out.push('\n');
        match &block.body {
            AssertBody::Wave(signals) if !signals.is_empty() => {
                generate_wave_assertion(block, signals, &mut out);
            }
            AssertBody::Wave(_) => {}
            AssertBody::Conditions(stmts) => {
                generate_condition_assertions(block, stmts, &mut out);
            }
        }
    }
    Some(out)
}

// ─── Approach A: wave pattern → SVA ──────────────────────────────────────────

#[derive(Debug, Clone, PartialEq)]
enum WaveState {
    High,
    Low,
    Data(String),
    X,
    Z,
    Clock,
    Gap,
}

#[derive(Debug, PartialEq)]
enum TriggerKind {
    Rose,
    Fell,
}

/// Expand a wave-expression sequence to a flat per-clock-cycle state list.
fn eval_waveform(seq: &[WaveExpr]) -> Vec<WaveState> {
    let mut states = Vec::new();
    for expr in seq {
        eval_expr(expr, &mut states);
    }
    states
}

fn eval_expr(expr: &WaveExpr, out: &mut Vec<WaveState>) {
    match expr {
        WaveExpr::Call { name, args, .. } => match name.as_str() {
            "high"  => { let n = wave_n(args); for _ in 0..n { out.push(WaveState::High); } }
            "low"   => { let n = wave_n(args); for _ in 0..n { out.push(WaveState::Low); } }
            "x"     => { let n = wave_n(args); for _ in 0..n { out.push(WaveState::X); } }
            "z"     => { let n = wave_n(args); for _ in 0..n { out.push(WaveState::Z); } }
            "clock" => { let n = wave_n(args); for _ in 0..n { out.push(WaveState::Clock); } }
            "gap"   => { out.push(WaveState::Gap); }
            "data"  => {
                let n = wave_n(args);
                let label = wave_label(args);
                for _ in 0..n {
                    out.push(WaveState::Data(label.clone()));
                }
            }
            _ => {}
        },
        WaveExpr::Repeat { count, sequence, .. } => {
            let mut sub = Vec::new();
            for e in sequence {
                eval_expr(e, &mut sub);
            }
            for _ in 0..*count {
                out.extend(sub.iter().cloned());
            }
        }
    }
}

fn wave_n(args: &[Arg]) -> usize {
    for arg in args {
        if let Arg::Positional(Value::Number(n), _) = arg {
            return *n as usize;
        }
    }
    1
}

fn wave_label(args: &[Arg]) -> String {
    let mut pos = 0usize;
    for arg in args {
        match arg {
            Arg::Positional(Value::Str(s), _) => {
                if pos == 1 {
                    return s.clone();
                }
                pos += 1;
            }
            Arg::Positional(_, _) => {
                pos += 1;
            }
            _ => {}
        }
    }
    String::new()
}

/// Find the first cycle where any signal transitions (X/Z → signal, Low → High, etc.).
/// Returns (signal_index, cycle_index, kind).
fn detect_trigger(waveforms: &[Vec<WaveState>]) -> Option<(usize, usize, TriggerKind)> {
    let max = waveforms.iter().map(|w| w.len()).max().unwrap_or(0);
    for cycle in 1..max {
        for (idx, wf) in waveforms.iter().enumerate() {
            if cycle >= wf.len() {
                continue;
            }
            let prev = &wf[cycle - 1];
            let curr = &wf[cycle];
            if prev == curr {
                continue;
            }
            // Skip clock/gap transitions — they're not protocol triggers.
            if matches!(prev, WaveState::Clock | WaveState::Gap) {
                continue;
            }
            if matches!(curr, WaveState::Clock | WaveState::Gap) {
                continue;
            }
            let kind = match curr {
                WaveState::High | WaveState::Data(_) => TriggerKind::Rose,
                _ => TriggerKind::Fell,
            };
            return Some((idx, cycle, kind));
        }
    }
    None
}

/// Last cycle (exclusive) containing at least one meaningful (non-X/Z/Clock/Gap) state.
fn find_useful_end(waveforms: &[Vec<WaveState>], from: usize) -> usize {
    let max = waveforms.iter().map(|w| w.len()).max().unwrap_or(0);
    let mut last = from;
    for cycle in from..max {
        let useful = waveforms.iter().any(|w| {
            cycle < w.len()
                && !matches!(w[cycle], WaveState::X | WaveState::Z | WaveState::Clock | WaveState::Gap)
        });
        if useful {
            last = cycle;
        }
    }
    if last >= from {
        last + 1
    } else {
        from
    }
}

/// Translate a single signal's state at one cycle into an SV condition string.
/// Returns `None` for don't-care states (X, Z, Clock, Gap).
fn state_to_sv_cond(signal: &str, state: &WaveState) -> Option<String> {
    match state {
        WaveState::High => Some(format!("{signal} == 1'b1")),
        WaveState::Low  => Some(format!("{signal} == 1'b0")),
        WaveState::Data(label) => {
            if let Some(hex) = parse_hex_digits(label) {
                let bits = hex.len() * 4;
                Some(format!("{signal} == {bits}'h{}", hex.to_uppercase()))
            } else {
                Some(format!("({signal} !== 'x && {signal} !== 'z)"))
            }
        }
        WaveState::X | WaveState::Z | WaveState::Clock | WaveState::Gap => None,
    }
}

/// Extract the hex digit string from "0x..." / "0X...", or return None.
fn parse_hex_digits(label: &str) -> Option<&str> {
    if let Some(rest) = label.strip_prefix("0x").or_else(|| label.strip_prefix("0X")) {
        if !rest.is_empty() && rest.chars().all(|c| c.is_ascii_hexdigit()) {
            return Some(rest);
        }
    }
    None
}

/// Compress consecutive identical condition strings: ["a","a","b"] → [("a",2),("b",1)].
fn compress_conditions(conds: &[String]) -> Vec<(String, usize)> {
    let mut out = Vec::new();
    let mut i = 0;
    while i < conds.len() {
        let cur = &conds[i];
        let mut n = 1;
        while i + n < conds.len() && &conds[i + n] == cur {
            n += 1;
        }
        out.push((cur.clone(), n));
        i += n;
    }
    out
}

fn generate_wave_assertion(block: &AssertBlock, signals: &[AssertSignal], out: &mut String) {
    let waveforms: Vec<Vec<WaveState>> = signals.iter().map(|s| eval_waveform(&s.sequence)).collect();

    match detect_trigger(&waveforms) {
        None => generate_wave_assertion_always(block, signals, &waveforms, out),
        Some((trig_idx, trig_cycle, kind)) => {
            let trig_name = &signals[trig_idx].name;
            let antecedent = match kind {
                TriggerKind::Rose => format!("$rose({trig_name})"),
                TriggerKind::Fell => format!("$fell({trig_name})"),
            };
            let useful_end = find_useful_end(&waveforms, trig_cycle);
            if useful_end <= trig_cycle {
                return;
            }

            let cycle_conds = build_cycle_conds(signals, &waveforms, trig_cycle, useful_end);
            if cycle_conds.is_empty() {
                return;
            }

            let consequent = format_consequent(&compress_conditions(&cycle_conds));

            out.push_str(&format!("// assert block: {}\n", block.name));
            out.push_str(&format!("property {};\n", block.name));
            out.push_str(&format!("    @(posedge {}) {antecedent} |->\n", block.clock));
            out.push_str(&format!("        {consequent};\n"));
            out.push_str("endproperty\n");
            out.push_str(&format!("assert property ({});\n", block.name));
        }
    }
}

fn generate_wave_assertion_always(
    block: &AssertBlock,
    signals: &[AssertSignal],
    waveforms: &[Vec<WaveState>],
    out: &mut String,
) {
    let useful_end = find_useful_end(waveforms, 0);
    if useful_end == 0 {
        return;
    }
    let cycle_conds = build_cycle_conds(signals, waveforms, 0, useful_end);
    if cycle_conds.is_empty() {
        return;
    }
    let consequent = format_consequent(&compress_conditions(&cycle_conds));

    out.push_str(&format!(
        "// assert block: {} (no trigger; full-pattern check)\n",
        block.name
    ));
    out.push_str(&format!("property {};\n", block.name));
    out.push_str(&format!("    @(posedge {}) 1 |->\n", block.clock));
    out.push_str(&format!("        {consequent};\n"));
    out.push_str("endproperty\n");
    out.push_str(&format!("assert property ({});\n", block.name));
}

/// Build per-cycle condition strings (AND of all signal conditions for that cycle).
fn build_cycle_conds(
    signals: &[AssertSignal],
    waveforms: &[Vec<WaveState>],
    from: usize,
    to: usize,
) -> Vec<String> {
    let mut cycle_conds: Vec<String> = Vec::new();
    for cycle in from..to {
        let per_sig: Vec<String> = signals
            .iter()
            .enumerate()
            .filter_map(|(i, sig)| {
                waveforms[i].get(cycle).and_then(|s| state_to_sv_cond(&sig.name, s))
            })
            .collect();
        if per_sig.is_empty() {
            cycle_conds.push("1".to_string());
        } else {
            cycle_conds.push(per_sig.join(" && "));
        }
    }
    // Trim trailing don't-care cycles.
    while cycle_conds.last().is_some_and(|s| s == "1") {
        cycle_conds.pop();
    }
    cycle_conds
}

fn format_consequent(compressed: &[(String, usize)]) -> String {
    let parts: Vec<String> = compressed
        .iter()
        .map(|(cond, n)| {
            if *n == 1 {
                format!("({cond})")
            } else {
                format!("({cond})[*{n}]")
            }
        })
        .collect();
    parts.join(" ##1\n        ")
}

// ─── when/then → SVA ─────────────────────────────────────────────────────────

fn generate_condition_assertions(block: &AssertBlock, stmts: &[WhenStmt], out: &mut String) {
    out.push_str(&format!("// assert block: {}\n", block.name));
    for (i, stmt) in stmts.iter().enumerate() {
        let prop_name = if stmts.len() == 1 {
            block.name.clone()
        } else {
            format!("{}_{i}", block.name)
        };
        let antecedent = cond_expr_to_sv(&stmt.antecedent);
        let consequent = seq_expr_to_sv(&stmt.consequent);

        out.push_str(&format!("property {prop_name};\n"));
        out.push_str(&format!("    @(posedge {}) ({antecedent}) |->\n", block.clock));
        out.push_str(&format!("        {consequent};\n"));
        out.push_str("endproperty\n");
        out.push_str(&format!("assert property ({prop_name});\n"));
    }
}

fn cond_expr_to_sv(expr: &CondExpr) -> String {
    match expr {
        CondExpr::Compare { signal, op, state, .. } => match (op, state) {
            (CmpOp::Eq, StateVal::High) => format!("{signal} == 1'b1"),
            (CmpOp::Eq, StateVal::Low)  => format!("{signal} == 1'b0"),
            (CmpOp::Eq, StateVal::X)    => format!("{signal} === 'x"),
            (CmpOp::Eq, StateVal::Z)    => format!("{signal} === 'z"),
            (CmpOp::Eq, StateVal::Data) => format!("({signal} !== 'x && {signal} !== 'z)"),
            (CmpOp::Ne, StateVal::High) => format!("{signal} != 1'b1"),
            (CmpOp::Ne, StateVal::Low)  => format!("{signal} != 1'b0"),
            (CmpOp::Ne, StateVal::X)    => format!("{signal} !== 'x"),
            (CmpOp::Ne, StateVal::Z)    => format!("{signal} !== 'z"),
            (CmpOp::Ne, StateVal::Data) => format!("({signal} === 'x || {signal} === 'z)"),
        },
        CondExpr::SysFunc { func, signal, .. } => {
            let f = match func {
                SysFunc::Rose   => "rose",
                SysFunc::Fell   => "fell",
                SysFunc::Stable => "stable",
            };
            format!("${f}({signal})")
        }
        CondExpr::And(l, r) => format!("({}) && ({})", cond_expr_to_sv(l), cond_expr_to_sv(r)),
        CondExpr::Or(l, r)  => format!("({}) || ({})", cond_expr_to_sv(l), cond_expr_to_sv(r)),
    }
}

fn seq_expr_to_sv(expr: &SeqExpr) -> String {
    match expr {
        SeqExpr::Delay { cycles, expr, .. } => {
            format!("##{cycles} {}", seq_expr_to_sv(expr))
        }
        SeqExpr::Cond(c) => format!("({})", cond_expr_to_sv(c)),
        SeqExpr::RepeatConsec { expr, count, .. } => {
            format!("({})[*{count}]", seq_expr_to_sv(expr))
        }
        SeqExpr::RepeatGoto { expr, count, .. } => {
            format!("({})[->{}]", seq_expr_to_sv(expr), count)
        }
        SeqExpr::And(l, r) => format!("({}) and ({})", seq_expr_to_sv(l), seq_expr_to_sv(r)),
        SeqExpr::Or(l, r)  => format!("({}) or ({})",  seq_expr_to_sv(l), seq_expr_to_sv(r)),
    }
}

// ─── Helpers with dead-Span suppression ──────────────────────────────────────

fn _span_dummy() -> Span {
    Span::new(0, 0)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::error::Span;

    fn sp() -> Span { Span::new(1, 1) }

    fn num_arg(n: u64) -> Arg { Arg::Positional(Value::Number(n), sp()) }
    fn str_arg(s: &str) -> Arg { Arg::Positional(Value::Str(s.to_string()), sp()) }

    fn call(name: &str, args: Vec<Arg>) -> WaveExpr {
        WaveExpr::Call { name: name.to_string(), args, span: sp() }
    }

    #[test]
    fn test_eval_low_high_low() {
        let seq = vec![
            call("low",  vec![num_arg(2)]),
            call("high", vec![num_arg(4)]),
            call("low",  vec![num_arg(2)]),
        ];
        let states = eval_waveform(&seq);
        assert_eq!(states.len(), 8);
        assert_eq!(states[0], WaveState::Low);
        assert_eq!(states[2], WaveState::High);
        assert_eq!(states[6], WaveState::Low);
    }

    #[test]
    fn test_eval_data_label() {
        let seq = vec![
            call("x",    vec![num_arg(2)]),
            call("data", vec![num_arg(4), str_arg("0xAB")]),
            call("x",    vec![num_arg(2)]),
        ];
        let states = eval_waveform(&seq);
        assert_eq!(states[2], WaveState::Data("0xAB".to_string()));
        assert_eq!(states[5], WaveState::Data("0xAB".to_string()));
        assert_eq!(states[6], WaveState::X);
    }

    #[test]
    fn test_detect_trigger_rose() {
        let wf = vec![
            WaveState::Low, WaveState::Low,
            WaveState::High, WaveState::High, WaveState::High, WaveState::High,
            WaveState::Low, WaveState::Low,
        ];
        let result = detect_trigger(&[wf]);
        assert!(matches!(result, Some((0, 2, TriggerKind::Rose))));
    }

    #[test]
    fn test_detect_trigger_fell() {
        let wf = vec![WaveState::High, WaveState::High, WaveState::Low, WaveState::Low];
        let result = detect_trigger(&[wf]);
        assert!(matches!(result, Some((0, 2, TriggerKind::Fell))));
    }

    #[test]
    fn test_detect_trigger_none() {
        let wf = vec![WaveState::X, WaveState::X, WaveState::X];
        assert!(detect_trigger(&[wf]).is_none());
    }

    #[test]
    fn test_compress_conditions() {
        let conds = vec![
            "a == 1".to_string(), "a == 1".to_string(),
            "a == 1".to_string(), "b == 0".to_string(),
        ];
        let c = compress_conditions(&conds);
        assert_eq!(c.len(), 2);
        assert_eq!(c[0], ("a == 1".to_string(), 3));
        assert_eq!(c[1], ("b == 0".to_string(), 1));
    }

    #[test]
    fn test_parse_hex_digits() {
        assert_eq!(parse_hex_digits("0xAB"), Some("AB"));
        assert_eq!(parse_hex_digits("0xFF"), Some("FF"));
        assert_eq!(parse_hex_digits("0X1A"), Some("1A"));
        assert_eq!(parse_hex_digits("CMD"),  None);
        assert_eq!(parse_hex_digits("0x"),   None); // empty hex
    }

    #[test]
    fn test_state_to_sv_cond() {
        assert_eq!(
            state_to_sv_cond("valid", &WaveState::High),
            Some("valid == 1'b1".to_string())
        );
        assert_eq!(
            state_to_sv_cond("d", &WaveState::Data("0xAB".to_string())),
            Some("d == 8'hAB".to_string())
        );
        assert_eq!(
            state_to_sv_cond("d", &WaveState::Data("CMD".to_string())),
            Some("(d !== 'x && d !== 'z)".to_string())
        );
        assert_eq!(state_to_sv_cond("s", &WaveState::X), None);
    }

    #[test]
    fn test_cond_expr_to_sv_compare() {
        let e = CondExpr::Compare {
            signal: "valid".to_string(), op: CmpOp::Eq, state: StateVal::High, span: sp(),
        };
        assert_eq!(cond_expr_to_sv(&e), "valid == 1'b1");
    }

    #[test]
    fn test_cond_expr_to_sv_sysfunc() {
        let e = CondExpr::SysFunc { func: SysFunc::Rose, signal: "clk".to_string(), span: sp() };
        assert_eq!(cond_expr_to_sv(&e), "$rose(clk)");
    }

    #[test]
    fn test_seq_expr_delay() {
        let inner = SeqExpr::Cond(CondExpr::Compare {
            signal: "d".to_string(), op: CmpOp::Ne, state: StateVal::X, span: sp(),
        });
        let e = SeqExpr::Delay { cycles: 2, expr: Box::new(inner), span: sp() };
        assert_eq!(seq_expr_to_sv(&e), "##2 (d !== 'x)");
    }
}
